import {
  Code2,
  Globe,
  Layout,
  Server,
  Coffee,
  Terminal,
  Cpu,
  BarChart3,
  Brain,
  Bot,
  Sparkles,
  Cloud,
  Wrench,
  ShieldCheck,
  TestTube,
  Users,
} from 'lucide-react';

export const ROLE_CATEGORIES = [
  { id: 'all', label: 'All Roles' },
  { id: 'engineering', label: 'Software & Web' },
  { id: 'languages', label: 'Languages' },
  { id: 'data_ai', label: 'Data & AI' },
  { id: 'cloud_devops', label: 'Cloud & DevOps' },
  { id: 'security_qa', label: 'Security & QA' },
  { id: 'hr', label: 'Behavioral & HR' },
];

export const ROLES = [
  {
    id: 'SDE',
    label: 'Software Engineer / SDE',
    shortLabel: 'SDE',
    icon: Code2,
    category: 'engineering',
    color: 'from-blue-500 to-cyan-500',
    glow: 'shadow-blue-500/20',
    border: 'border-blue-500/30',
    badge: 'bg-blue-500/10 text-blue-400 border-blue-500/20',
    description: 'DSA, system design, OOP, architecture & clean code',
    tags: ['Data Structures', 'Algorithms', 'System Design', 'OOP'],
  },
  {
    id: 'Full Stack Developer',
    label: 'Full Stack Developer',
    shortLabel: 'Full Stack',
    icon: Globe,
    category: 'engineering',
    color: 'from-indigo-500 to-blue-500',
    glow: 'shadow-indigo-500/20',
    border: 'border-indigo-500/30',
    badge: 'bg-indigo-500/10 text-indigo-400 border-indigo-500/20',
    description: 'Frontend UI, REST/GraphQL APIs, databases & full application flow',
    tags: ['React/Next.js', 'Node.js', 'APIs', 'Databases'],
  },
  {
    id: 'Frontend Developer',
    label: 'Frontend Developer',
    shortLabel: 'Frontend',
    icon: Layout,
    category: 'engineering',
    color: 'from-pink-500 to-rose-500',
    glow: 'shadow-pink-500/20',
    border: 'border-pink-500/30',
    badge: 'bg-pink-500/10 text-pink-400 border-pink-500/20',
    description: 'UI/UX design systems, HTML/CSS, JavaScript/TypeScript & React',
    tags: ['JavaScript', 'React', 'CSS/Tailwind', 'Performance'],
  },
  {
    id: 'Backend Developer',
    label: 'Backend Developer',
    shortLabel: 'Backend',
    icon: Server,
    category: 'engineering',
    color: 'from-amber-500 to-orange-500',
    glow: 'shadow-amber-500/20',
    border: 'border-amber-500/30',
    badge: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
    description: 'Server architecture, API design, database tuning & microservices',
    tags: ['Node.js/Express', 'SQL/NoSQL', 'Microservices', 'Caching'],
  },
  {
    id: 'Java Developer',
    label: 'Java Developer',
    shortLabel: 'Java',
    icon: Coffee,
    category: 'languages',
    color: 'from-red-500 to-orange-500',
    glow: 'shadow-red-500/20',
    border: 'border-red-500/30',
    badge: 'bg-red-500/10 text-red-400 border-red-500/20',
    description: 'Core Java, Spring Boot, Multithreading, JVM internals & OOP design',
    tags: ['Core Java', 'Spring Boot', 'Multithreading', 'Design Patterns'],
  },
  {
    id: 'Python Developer',
    label: 'Python Developer',
    shortLabel: 'Python',
    icon: Terminal,
    category: 'languages',
    color: 'from-yellow-500 to-amber-500',
    glow: 'shadow-yellow-500/20',
    border: 'border-yellow-500/30',
    badge: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/20',
    description: 'Python core, Django/FastAPI, AsyncIO, scripting & backend services',
    tags: ['Python 3', 'FastAPI/Django', 'AsyncIO', 'Data Processing'],
  },
  {
    id: 'C++ Developer',
    label: 'C++ Developer',
    shortLabel: 'C++',
    icon: Cpu,
    category: 'languages',
    color: 'from-cyan-500 to-blue-600',
    glow: 'shadow-cyan-500/20',
    border: 'border-cyan-500/30',
    badge: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
    description: 'Memory management, Pointers, STL, modern C++20 & low-level design',
    tags: ['C++17/20', 'STL', 'Pointers/Memory', 'Multithreading'],
  },
  {
    id: 'Data Analyst',
    label: 'Data Analyst',
    shortLabel: 'Data Analyst',
    icon: BarChart3,
    category: 'data_ai',
    color: 'from-emerald-500 to-teal-500',
    glow: 'shadow-emerald-500/20',
    border: 'border-emerald-500/30',
    badge: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    description: 'SQL queries, business intelligence, data visualization & statistics',
    tags: ['Complex SQL', 'Excel/PowerBI', 'Statistics', 'EDA'],
  },
  {
    id: 'Data Scientist',
    label: 'Data Scientist',
    shortLabel: 'Data Scientist',
    icon: Brain,
    category: 'data_ai',
    color: 'from-teal-500 to-cyan-500',
    glow: 'shadow-teal-500/20',
    border: 'border-teal-500/30',
    badge: 'bg-teal-500/10 text-teal-400 border-teal-500/20',
    description: 'Predictive modeling, Pandas/Scikit-Learn, hypothesis testing & ML',
    tags: ['Pandas/NumPy', 'Scikit-Learn', 'Statistical Modeling', 'A/B Testing'],
  },
  {
    id: 'Machine Learning Engineer',
    label: 'Machine Learning Engineer',
    shortLabel: 'ML Engineer',
    icon: Bot,
    category: 'data_ai',
    color: 'from-purple-500 to-indigo-500',
    glow: 'shadow-purple-500/20',
    border: 'border-purple-500/30',
    badge: 'bg-purple-500/10 text-purple-400 border-purple-500/20',
    description: 'Deep Learning, PyTorch/TensorFlow, model training & MLOps pipelines',
    tags: ['PyTorch', 'TensorFlow', 'MLOps', 'Model Deployment'],
  },
  {
    id: 'AI Engineer',
    label: 'AI Engineer',
    shortLabel: 'AI Engineer',
    icon: Sparkles,
    category: 'data_ai',
    color: 'from-fuchsia-500 to-purple-500',
    glow: 'shadow-fuchsia-500/20',
    border: 'border-fuchsia-500/30',
    badge: 'bg-fuchsia-500/10 text-fuchsia-400 border-fuchsia-500/20',
    description: 'LLMs, RAG architectures, prompt engineering, fine-tuning & AI apps',
    tags: ['LLMs & RAG', 'LangChain/LlamaIndex', 'Embeddings', 'Prompting'],
  },
  {
    id: 'Cloud Engineer',
    label: 'Cloud Engineer',
    shortLabel: 'Cloud',
    icon: Cloud,
    category: 'cloud_devops',
    color: 'from-sky-500 to-blue-500',
    glow: 'shadow-sky-500/20',
    border: 'border-sky-500/30',
    badge: 'bg-sky-500/10 text-sky-400 border-sky-500/20',
    description: 'AWS/Azure services, cloud security, infrastructure & scalability',
    tags: ['AWS/Azure', 'Terraform', 'IAM & VPC', 'Serverless'],
  },
  {
    id: 'DevOps Engineer',
    label: 'DevOps Engineer',
    shortLabel: 'DevOps',
    icon: Wrench,
    category: 'cloud_devops',
    color: 'from-orange-500 to-red-500',
    glow: 'shadow-orange-500/20',
    border: 'border-orange-500/30',
    badge: 'bg-orange-500/10 text-orange-400 border-orange-500/20',
    description: 'CI/CD pipelines, Docker, Kubernetes, monitoring & infrastructure as code',
    tags: ['Docker & K8s', 'CI/CD Pipelines', 'GitHub Actions', 'Monitoring'],
  },
  {
    id: 'Cybersecurity Analyst',
    label: 'Cybersecurity Analyst',
    shortLabel: 'Cyber Security',
    icon: ShieldCheck,
    category: 'security_qa',
    color: 'from-emerald-600 to-green-500',
    glow: 'shadow-green-500/20',
    border: 'border-green-500/30',
    badge: 'bg-green-500/10 text-green-400 border-green-500/20',
    description: 'Network security, vulnerability assessments, SIEM, cryptography & compliance',
    tags: ['Network Security', 'OWASP Top 10', 'PenTesting', 'SIEM'],
  },
  {
    id: 'QA / Test Engineer',
    label: 'QA / Test Engineer',
    shortLabel: 'QA Engineer',
    icon: TestTube,
    category: 'security_qa',
    color: 'from-violet-500 to-fuchsia-500',
    glow: 'shadow-violet-500/20',
    border: 'border-violet-500/30',
    badge: 'bg-violet-500/10 text-violet-400 border-violet-500/20',
    description: 'Test automation, Selenium/Cypress, API testing & test plan design',
    tags: ['Test Automation', 'Selenium/Cypress', 'API Testing', 'Bug Tracking'],
  },
  {
    id: 'HR',
    label: 'Human Resources / HR',
    shortLabel: 'HR',
    icon: Users,
    category: 'hr',
    color: 'from-purple-500 to-pink-500',
    glow: 'shadow-purple-500/20',
    border: 'border-purple-500/30',
    badge: 'bg-purple-500/10 text-purple-400 border-purple-500/20',
    description: 'Behavioral STAR questions, communication, teamwork & culture fit',
    tags: ['Behavioral', 'STAR Method', 'Leadership', 'Conflict Resolution'],
  },
];
